/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OrderSuccessRouteImport } from './routes/order-success'
import { Route as LoginRouteImport } from './routes/login'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as DeliveryRouteImport } from './routes/delivery'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AccountLoginRouteImport } from './routes/account-login'
import { Route as AccountRouteImport } from './routes/account'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as NewsIndexRouteImport } from './routes/news.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as NewsSlugRouteImport } from './routes/news.$slug'
import { Route as AdminWarehouseRouteImport } from './routes/admin.warehouse'
import { Route as AdminTrashRouteImport } from './routes/admin.trash'
import { Route as AdminShiftsRouteImport } from './routes/admin.shifts'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminReportsRouteImport } from './routes/admin.reports'
import { Route as AdminPromosRouteImport } from './routes/admin.promos'
import { Route as AdminProductsRouteImport } from './routes/admin.products'
import { Route as AdminPosRouteImport } from './routes/admin.pos'
import { Route as AdminOrdersRouteImport } from './routes/admin.orders'
import { Route as AdminNewsRouteImport } from './routes/admin.news'
import { Route as AdminModifiersRouteImport } from './routes/admin.modifiers'
import { Route as AdminKanbanRouteImport } from './routes/admin.kanban'
import { Route as AdminInventoryRouteImport } from './routes/admin.inventory'
import { Route as AdminExpensesRouteImport } from './routes/admin.expenses'
import { Route as AdminCustomersRouteImport } from './routes/admin.customers'
import { Route as AdminCouriersRouteImport } from './routes/admin.couriers'
import { Route as AdminCategoriesRouteImport } from './routes/admin.categories'
import { Route as AdminCallbacksRouteImport } from './routes/admin.callbacks'
import { Route as AdminBranchesRouteImport } from './routes/admin.branches'
import { Route as AdminBannersRouteImport } from './routes/admin.banners'

const OrderSuccessRoute = OrderSuccessRouteImport.update({
  id: '/order-success',
  path: '/order-success',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const DeliveryRoute = DeliveryRouteImport.update({
  id: '/delivery',
  path: '/delivery',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountLoginRoute = AccountLoginRouteImport.update({
  id: '/account-login',
  path: '/account-login',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsIndexRoute = NewsIndexRouteImport.update({
  id: '/news/',
  path: '/news/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const NewsSlugRoute = NewsSlugRouteImport.update({
  id: '/news/$slug',
  path: '/news/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminWarehouseRoute = AdminWarehouseRouteImport.update({
  id: '/warehouse',
  path: '/warehouse',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTrashRoute = AdminTrashRouteImport.update({
  id: '/trash',
  path: '/trash',
  getParentRoute: () => AdminRoute,
} as any)
const AdminShiftsRoute = AdminShiftsRouteImport.update({
  id: '/shifts',
  path: '/shifts',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPromosRoute = AdminPromosRouteImport.update({
  id: '/promos',
  path: '/promos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProductsRoute = AdminProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPosRoute = AdminPosRouteImport.update({
  id: '/pos',
  path: '/pos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrdersRoute = AdminOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNewsRoute = AdminNewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => AdminRoute,
} as any)
const AdminModifiersRoute = AdminModifiersRouteImport.update({
  id: '/modifiers',
  path: '/modifiers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminKanbanRoute = AdminKanbanRouteImport.update({
  id: '/kanban',
  path: '/kanban',
  getParentRoute: () => AdminRoute,
} as any)
const AdminInventoryRoute = AdminInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => AdminRoute,
} as any)
const AdminExpensesRoute = AdminExpensesRouteImport.update({
  id: '/expenses',
  path: '/expenses',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCustomersRoute = AdminCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCouriersRoute = AdminCouriersRouteImport.update({
  id: '/couriers',
  path: '/couriers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCategoriesRoute = AdminCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCallbacksRoute = AdminCallbacksRouteImport.update({
  id: '/callbacks',
  path: '/callbacks',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBranchesRoute = AdminBranchesRouteImport.update({
  id: '/branches',
  path: '/branches',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBannersRoute = AdminBannersRouteImport.update({
  id: '/banners',
  path: '/banners',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/account-login': typeof AccountLoginRoute
  '/admin': typeof AdminRouteWithChildren
  '/checkout': typeof CheckoutRoute
  '/delivery': typeof DeliveryRoute
  '/faq': typeof FaqRoute
  '/login': typeof LoginRoute
  '/order-success': typeof OrderSuccessRoute
  '/admin/banners': typeof AdminBannersRoute
  '/admin/branches': typeof AdminBranchesRoute
  '/admin/callbacks': typeof AdminCallbacksRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/couriers': typeof AdminCouriersRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/expenses': typeof AdminExpensesRoute
  '/admin/inventory': typeof AdminInventoryRoute
  '/admin/kanban': typeof AdminKanbanRoute
  '/admin/modifiers': typeof AdminModifiersRoute
  '/admin/news': typeof AdminNewsRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/pos': typeof AdminPosRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/promos': typeof AdminPromosRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/shifts': typeof AdminShiftsRoute
  '/admin/trash': typeof AdminTrashRoute
  '/admin/warehouse': typeof AdminWarehouseRoute
  '/news/$slug': typeof NewsSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/news/': typeof NewsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/account-login': typeof AccountLoginRoute
  '/checkout': typeof CheckoutRoute
  '/delivery': typeof DeliveryRoute
  '/faq': typeof FaqRoute
  '/login': typeof LoginRoute
  '/order-success': typeof OrderSuccessRoute
  '/admin/banners': typeof AdminBannersRoute
  '/admin/branches': typeof AdminBranchesRoute
  '/admin/callbacks': typeof AdminCallbacksRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/couriers': typeof AdminCouriersRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/expenses': typeof AdminExpensesRoute
  '/admin/inventory': typeof AdminInventoryRoute
  '/admin/kanban': typeof AdminKanbanRoute
  '/admin/modifiers': typeof AdminModifiersRoute
  '/admin/news': typeof AdminNewsRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/pos': typeof AdminPosRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/promos': typeof AdminPromosRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/shifts': typeof AdminShiftsRoute
  '/admin/trash': typeof AdminTrashRoute
  '/admin/warehouse': typeof AdminWarehouseRoute
  '/news/$slug': typeof NewsSlugRoute
  '/admin': typeof AdminIndexRoute
  '/news': typeof NewsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/account-login': typeof AccountLoginRoute
  '/admin': typeof AdminRouteWithChildren
  '/checkout': typeof CheckoutRoute
  '/delivery': typeof DeliveryRoute
  '/faq': typeof FaqRoute
  '/login': typeof LoginRoute
  '/order-success': typeof OrderSuccessRoute
  '/admin/banners': typeof AdminBannersRoute
  '/admin/branches': typeof AdminBranchesRoute
  '/admin/callbacks': typeof AdminCallbacksRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/couriers': typeof AdminCouriersRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/expenses': typeof AdminExpensesRoute
  '/admin/inventory': typeof AdminInventoryRoute
  '/admin/kanban': typeof AdminKanbanRoute
  '/admin/modifiers': typeof AdminModifiersRoute
  '/admin/news': typeof AdminNewsRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/pos': typeof AdminPosRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/promos': typeof AdminPromosRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/shifts': typeof AdminShiftsRoute
  '/admin/trash': typeof AdminTrashRoute
  '/admin/warehouse': typeof AdminWarehouseRoute
  '/news/$slug': typeof NewsSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/news/': typeof NewsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/account'
    | '/account-login'
    | '/admin'
    | '/checkout'
    | '/delivery'
    | '/faq'
    | '/login'
    | '/order-success'
    | '/admin/banners'
    | '/admin/branches'
    | '/admin/callbacks'
    | '/admin/categories'
    | '/admin/couriers'
    | '/admin/customers'
    | '/admin/expenses'
    | '/admin/inventory'
    | '/admin/kanban'
    | '/admin/modifiers'
    | '/admin/news'
    | '/admin/orders'
    | '/admin/pos'
    | '/admin/products'
    | '/admin/promos'
    | '/admin/reports'
    | '/admin/settings'
    | '/admin/shifts'
    | '/admin/trash'
    | '/admin/warehouse'
    | '/news/$slug'
    | '/admin/'
    | '/news/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/account'
    | '/account-login'
    | '/checkout'
    | '/delivery'
    | '/faq'
    | '/login'
    | '/order-success'
    | '/admin/banners'
    | '/admin/branches'
    | '/admin/callbacks'
    | '/admin/categories'
    | '/admin/couriers'
    | '/admin/customers'
    | '/admin/expenses'
    | '/admin/inventory'
    | '/admin/kanban'
    | '/admin/modifiers'
    | '/admin/news'
    | '/admin/orders'
    | '/admin/pos'
    | '/admin/products'
    | '/admin/promos'
    | '/admin/reports'
    | '/admin/settings'
    | '/admin/shifts'
    | '/admin/trash'
    | '/admin/warehouse'
    | '/news/$slug'
    | '/admin'
    | '/news'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/account'
    | '/account-login'
    | '/admin'
    | '/checkout'
    | '/delivery'
    | '/faq'
    | '/login'
    | '/order-success'
    | '/admin/banners'
    | '/admin/branches'
    | '/admin/callbacks'
    | '/admin/categories'
    | '/admin/couriers'
    | '/admin/customers'
    | '/admin/expenses'
    | '/admin/inventory'
    | '/admin/kanban'
    | '/admin/modifiers'
    | '/admin/news'
    | '/admin/orders'
    | '/admin/pos'
    | '/admin/products'
    | '/admin/promos'
    | '/admin/reports'
    | '/admin/settings'
    | '/admin/shifts'
    | '/admin/trash'
    | '/admin/warehouse'
    | '/news/$slug'
    | '/admin/'
    | '/news/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AccountRoute: typeof AccountRoute
  AccountLoginRoute: typeof AccountLoginRoute
  AdminRoute: typeof AdminRouteWithChildren
  CheckoutRoute: typeof CheckoutRoute
  DeliveryRoute: typeof DeliveryRoute
  FaqRoute: typeof FaqRoute
  LoginRoute: typeof LoginRoute
  OrderSuccessRoute: typeof OrderSuccessRoute
  NewsSlugRoute: typeof NewsSlugRoute
  NewsIndexRoute: typeof NewsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/order-success': {
      id: '/order-success'
      path: '/order-success'
      fullPath: '/order-success'
      preLoaderRoute: typeof OrderSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/delivery': {
      id: '/delivery'
      path: '/delivery'
      fullPath: '/delivery'
      preLoaderRoute: typeof DeliveryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account-login': {
      id: '/account-login'
      path: '/account-login'
      fullPath: '/account-login'
      preLoaderRoute: typeof AccountLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news/': {
      id: '/news/'
      path: '/news'
      fullPath: '/news/'
      preLoaderRoute: typeof NewsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/news/$slug': {
      id: '/news/$slug'
      path: '/news/$slug'
      fullPath: '/news/$slug'
      preLoaderRoute: typeof NewsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/warehouse': {
      id: '/admin/warehouse'
      path: '/warehouse'
      fullPath: '/admin/warehouse'
      preLoaderRoute: typeof AdminWarehouseRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/trash': {
      id: '/admin/trash'
      path: '/trash'
      fullPath: '/admin/trash'
      preLoaderRoute: typeof AdminTrashRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/shifts': {
      id: '/admin/shifts'
      path: '/shifts'
      fullPath: '/admin/shifts'
      preLoaderRoute: typeof AdminShiftsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/promos': {
      id: '/admin/promos'
      path: '/promos'
      fullPath: '/admin/promos'
      preLoaderRoute: typeof AdminPromosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/products': {
      id: '/admin/products'
      path: '/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AdminProductsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/pos': {
      id: '/admin/pos'
      path: '/pos'
      fullPath: '/admin/pos'
      preLoaderRoute: typeof AdminPosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/orders': {
      id: '/admin/orders'
      path: '/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AdminOrdersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/news': {
      id: '/admin/news'
      path: '/news'
      fullPath: '/admin/news'
      preLoaderRoute: typeof AdminNewsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/modifiers': {
      id: '/admin/modifiers'
      path: '/modifiers'
      fullPath: '/admin/modifiers'
      preLoaderRoute: typeof AdminModifiersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/kanban': {
      id: '/admin/kanban'
      path: '/kanban'
      fullPath: '/admin/kanban'
      preLoaderRoute: typeof AdminKanbanRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/inventory': {
      id: '/admin/inventory'
      path: '/inventory'
      fullPath: '/admin/inventory'
      preLoaderRoute: typeof AdminInventoryRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/expenses': {
      id: '/admin/expenses'
      path: '/expenses'
      fullPath: '/admin/expenses'
      preLoaderRoute: typeof AdminExpensesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/customers': {
      id: '/admin/customers'
      path: '/customers'
      fullPath: '/admin/customers'
      preLoaderRoute: typeof AdminCustomersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/couriers': {
      id: '/admin/couriers'
      path: '/couriers'
      fullPath: '/admin/couriers'
      preLoaderRoute: typeof AdminCouriersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/categories': {
      id: '/admin/categories'
      path: '/categories'
      fullPath: '/admin/categories'
      preLoaderRoute: typeof AdminCategoriesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/callbacks': {
      id: '/admin/callbacks'
      path: '/callbacks'
      fullPath: '/admin/callbacks'
      preLoaderRoute: typeof AdminCallbacksRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/branches': {
      id: '/admin/branches'
      path: '/branches'
      fullPath: '/admin/branches'
      preLoaderRoute: typeof AdminBranchesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/banners': {
      id: '/admin/banners'
      path: '/banners'
      fullPath: '/admin/banners'
      preLoaderRoute: typeof AdminBannersRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminBannersRoute: typeof AdminBannersRoute
  AdminBranchesRoute: typeof AdminBranchesRoute
  AdminCallbacksRoute: typeof AdminCallbacksRoute
  AdminCategoriesRoute: typeof AdminCategoriesRoute
  AdminCouriersRoute: typeof AdminCouriersRoute
  AdminCustomersRoute: typeof AdminCustomersRoute
  AdminExpensesRoute: typeof AdminExpensesRoute
  AdminInventoryRoute: typeof AdminInventoryRoute
  AdminKanbanRoute: typeof AdminKanbanRoute
  AdminModifiersRoute: typeof AdminModifiersRoute
  AdminNewsRoute: typeof AdminNewsRoute
  AdminOrdersRoute: typeof AdminOrdersRoute
  AdminPosRoute: typeof AdminPosRoute
  AdminProductsRoute: typeof AdminProductsRoute
  AdminPromosRoute: typeof AdminPromosRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminShiftsRoute: typeof AdminShiftsRoute
  AdminTrashRoute: typeof AdminTrashRoute
  AdminWarehouseRoute: typeof AdminWarehouseRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminBannersRoute: AdminBannersRoute,
  AdminBranchesRoute: AdminBranchesRoute,
  AdminCallbacksRoute: AdminCallbacksRoute,
  AdminCategoriesRoute: AdminCategoriesRoute,
  AdminCouriersRoute: AdminCouriersRoute,
  AdminCustomersRoute: AdminCustomersRoute,
  AdminExpensesRoute: AdminExpensesRoute,
  AdminInventoryRoute: AdminInventoryRoute,
  AdminKanbanRoute: AdminKanbanRoute,
  AdminModifiersRoute: AdminModifiersRoute,
  AdminNewsRoute: AdminNewsRoute,
  AdminOrdersRoute: AdminOrdersRoute,
  AdminPosRoute: AdminPosRoute,
  AdminProductsRoute: AdminProductsRoute,
  AdminPromosRoute: AdminPromosRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminShiftsRoute: AdminShiftsRoute,
  AdminTrashRoute: AdminTrashRoute,
  AdminWarehouseRoute: AdminWarehouseRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AccountRoute: AccountRoute,
  AccountLoginRoute: AccountLoginRoute,
  AdminRoute: AdminRouteWithChildren,
  CheckoutRoute: CheckoutRoute,
  DeliveryRoute: DeliveryRoute,
  FaqRoute: FaqRoute,
  LoginRoute: LoginRoute,
  OrderSuccessRoute: OrderSuccessRoute,
  NewsSlugRoute: NewsSlugRoute,
  NewsIndexRoute: NewsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
